apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: nuam-bridge-test
  namespace: strimzi-kafka
spec:
  replicas: 1
  bootstrapServers: nuam-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
    - secretName: nuam-cluster-cluster-ca-cert
      certificate: ca.crt
  authentication:
    type: tls
    certificateAndKey:
      secretName: user-bridge
      certificate: user.crt
      key: user.key
  http:
    port: 8088
 # logging:
 #   type: inline
 #   loggers:
#      logger.bridge.level: DEBUG
#      logger.send.name: "http.nuam.operation.send"
#      logger.send.level: DEBUG