apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: bus-app-test-flux
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bus-app-test-flux
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
  type: ClusterIP

