apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: strimzi-kafka
spec:
  releaseName: kafka-ui
  chart:
    spec:
      chart: kafka-ui
      sourceRef:
        kind: HelmRepository
        name: provectus-kafka-ui
        namespace: flux-system
      version: "0.7.5"  
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
  interval: 24h0m0s
  values:
    yamlApplicationConfig:
      kafka:
        clusters:
          - name: nuam-cluster
            bootstrapServers: nuam-cluster-kafka-bootstrap.strimzi-kafka:9092
            properties:
              security.protocol: SASL_PLAINTEXT
              sasl.mechanism: SCRAM-SHA-512 
              sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="gui-user" password="c46bHH4Tcoq8sXj3iYcNDnrejagmhTtF";
      auth:
        type: OAUTH2
        oauth2:
          client:
             keycloak:
                 clientId: KafkaUI
                 clientSecret: qVipCL3Bbd3AihF7cqDaxWhFkG4lqVt5
                 scope: openid
                 issuer-uri: http://localhost:9090/realms/master
                 user-name-attribute: preferred_username
                 client-name: keycloak
                 provider: keycloak
                 custom-params:
                     type: oauth
                     roles-field: groups
      management:
        health:
          ldap:
            enabled: false
      rbac:
        enabled: true
        roles:
        - name: "admins"
            clusters:
            - clusters
            subjects:
            - provider: oauth
                type: role
                value: "Admin"
            permissions:
            - resource: applicationconfig
                actions: ["view", "edit", "create", "delete"]
            
            - resource: clusterconfig
                actions: ["view", "edit", "create", "delete"]
        
            - resource: topic
                value: ".*"
                actions: ["view", "edit", "create", "delete"]
        
            - resource: consumer
                value: ".*"
                actions: ["view", "edit", "create", "delete"]
        
            - resource: schema
                value: ".*"
                actions: ["view", "edit", "create", "delete"]
        
            - resource: connect
                value: ".*"
                actions: ["view", "edit", "create", "delete"]
        
            - resource: ksql
                actions: ["view", "edit", "create", "delete"]
        - name: "readonly"
            clusters:
            - clusters
            subjects:
            - provider: oauth
                type: role
                value: "Viewer"
        
            permissions:
            - resource: clusterconfig
                actions: [ "view" ]
        
            - resource: topic
                value: ".*"
                actions: 
                - VIEW
                - MESSAGES_READ
        
            - resource: consumer
                value: ".*"
                actions: [ "view" ]
        
            - resource: schema
                value: ".*"
                actions: [ "view" ]
        
            - resource: connect
                value: ".*"
                actions: [ "view" ]