apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-ui
  namespace: strimzi-kafka
spec:
spec:
  containers:
  - env:
    - name: SPRING_CONFIG_ADDITIONAL-LOCATION
      value: /kafka-ui/config.yml
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /actuator/health
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    name: kafka-ui
    ports:
    - containerPort: 9090
      name: http
      protocol: TCP
  releaseName: kafka-ui
  chart:
    spec:
      chart: kafka-ui
      sourceRef:
        kind: HelmRepository
        name: provectus-kafka-ui
        namespace: flux-system
      version: "0.7.5"  
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
  interval: 24h0m0s
  
  values:
    yamlApplicationConfig:
      kafka:
        clusters:
          - name: nuam-cluster
            bootstrapServers: nuam-cluster-kafka-bootstrap.strimzi-kafka:9092
            properties:
              security.protocol: SASL_PLAINTEXT
              sasl.mechanism: SCRAM-SHA-512 
              sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="gui--user" password="c46bHH4Tcoq8sXj3iYcNDnrejagmhTtF";
            server:
                port: 10000
      auth:
        type: disabled
      management:
        health:
          ldap:
            enabled: false