apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: nuam-cluster
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: nuam-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: nuam-cluster
  namespace: strimzi-kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    # Released Jul 21, 2023
    version: 3.5.1 
    # The replicas field is required by the Kafka CRD schema while the KafkaNodePools feature gate is in alpha phase.
    # But it will be ignored when Kafka Node Pools are used
    replicas: 3
    authorization:
      type: simple
    listeners:
      - name: gui
        port: 9092
        type: internal
        tls: false       
        authentication:
           type: scram-sha-512
      - name: internal
        port: 9093
        type: internal
        tls: true
        authentication:
           type: tls
#      - name: oauth
#        port: 9094
#        type: internal
#        tls: false
#        authentication:
#          type: oauth
#          validIssuerUri: http://localhost:9090/auth/realms/demo
#          jwksEndpointUri: http://localhost:9090/auth/realms/demo/protocol/openid-connect/certs
#          userNameClaim: user_admin
      - name: external
        port: 9095
        type: nodeport
        tls: true
        authentication:
           type: tls
        configuration:
           preferredNodePortAddressType: InternalDNS
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      ssl.enabled.protocols: TLSv1.3, TLSv1.2
      ssl.protocol: TLSv1.2
      auto.create.topics.enable: false
      # The broker protocol version is required by upgrade kafka
      inter.broker.protocol.version: "3.5" 
    # The storage field is required by the Kafka CRD schema while the KafkaNodePools feature gate is in alpha phase.
    # But it will be ignored when Kafka Node Pools are used
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
  # The ZooKeeper section is required by the Kafka CRD schema while the UseKRaft feature gate is in alpha phase.
  # But it will be ignored when running in KRaft mode
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    # Enable Strimzi TopicOperator for KafkaTopic CRDs
    topicOperator: {}
    # Enable Strimzi UserOperator for KafkaUser CRDs
    userOperator: {}
    