apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic-one-partition
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: nuam-cluster
spec:
  partitions: 1
  replicas: 2
  config:
    # This configuration controls the maximum time we will retain a log before we will discard old log segments to free up space if we are using the “delete” retention policy. This represents an SLA on how soon consumers must read their data. If set to -1, no time limit is applied.
    # Default 604800000 (7 days)
    retention.ms: 604800000
    # This configuration controls the segment file size for the log. Retention and cleaning is always done a file at a time so a larger segment size means fewer files but less granular control over retention.
    # Default 1073741824 (1 gibibyte)
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic-two-partition
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: nuam-cluster
spec:
  partitions: 2
  replicas: 2
  config:
    # This configuration controls the maximum time we will retain a log before we will discard old log segments to free up space if we are using the “delete” retention policy. This represents an SLA on how soon consumers must read their data. If set to -1, no time limit is applied.
    # Default 604800000 (7 days)
    retention.ms: 604800000
    # This configuration controls the segment file size for the log. Retention and cleaning is always done a file at a time so a larger segment size means fewer files but less granular control over retention.
    # Default 1073741824 (1 gibibyte)
    segment.bytes: 1073741824